#!/bin/bash

coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_brp2_4_prop2_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_needham_1_prop4_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_brp2_2_prop3_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_brp_5_prop1_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_pgm_protocol_4_prop6_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_elevator_3_prop1_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_iprotocol_7_prop1_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_counter_v_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_lifts_3_prop1_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_resistance_1_prop2_ab_cti_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_pouring_2_prop1_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_brp2_3_prop3_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/2018-Goel-hwbench/QF_UF_elevator_2_prop1_ab_reg_max.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/SEQ/SEQ038_size7.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/20170829-Rodin/smt249825283571301584.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl374.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl509.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl036.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/dead_dnd032.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/dead_dnd002.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1106.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl600.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn1104.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn223.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/dead_dnd031.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl515.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn420.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1219.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl308.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl160.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl692.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn235.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl335.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl505.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn1058.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn425.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl142.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl042.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl005.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl016.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn180.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl487.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl726.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl599.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl143.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl473.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl906.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn588.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn750.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn114.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl080.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1251.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl713.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl204.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl248.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl679.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl887.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl353.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl221.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl150.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl1217.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1009.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl184.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl874.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl070.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl063.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn749.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/dead_dnd041.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl748.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl050.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl330.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl576.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/dead_dnd007.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl1265.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl212.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl813.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl653.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn1279.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl159.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl972.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl866.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl132.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl561.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn009.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl911.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl720.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl783.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1046.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl631.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl096.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1280.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl904.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn1231.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn1086.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl760.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn1047.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl949.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl954.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl815.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl986.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl774.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl178.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl865.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl432.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl379.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn942.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl636.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn1126.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl416.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl944.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl075.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn1092.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn1103.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl1051.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl842.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl583.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl538.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl498.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl123.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl539.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl832.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl249.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl945.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl468.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1055.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl112.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl220.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl651.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl896.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl823.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl970.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl238.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl217.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1223.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/dead_dnd036.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1044.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn658.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1259.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn484.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn869.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn317.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1153.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn526.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1261.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl288.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn507.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl075.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl582.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn411.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn307.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1270.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl839.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl870.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn606.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn1212.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl658.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl964.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl312.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl010.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl115.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn998.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl336.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl183.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn261.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl463.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl1236.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl935.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl190.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl547.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl1131.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn900.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl1255.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl271.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl969.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl825.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl218.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_brn023.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl353.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl299.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl1097.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/gensys_icl891.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_brn1097.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg5/iso_icl922.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg7/iso_icl002.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg7/iso_brn004.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg7/iso_icl_sk002.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg7/iso_brn_sk036.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg7/iso_icl_repgen_sk006.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg7/iso_brn023.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/gensys_icl100.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/gensys_icl044.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/iso_brn005.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/iso_brn028.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/gensys_icl064.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/gensys_icl084.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/gensys_icl099.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/iso_icl038.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/gensys_icl019.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/iso_icl082.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/dead_dnd016.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/iso_icl083.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/iso_brn033.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/iso_icl071.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/gensys_brn089.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/loops6/gensys_icl055.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/QG-classification/qg6/iso_icl012.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/NEQ/NEQ033_size5.v
coqc /home/arjun/Desktop/smtcoq/arjunvish-smtcoq-veritAst/smtcoq/examples/thesis-exp/QF_UF/NEQ/NEQ027_size8.v
