(* Demonstrates the process_trans stack-overflow fix, the same way stack_overflow_cong
   demonstrates it for process_cong (see that directory's .v file and CLAUDE.md for the general
   mechanism: the old process_trans_aux recursed as `step :: process_trans_aux tl cog` for
   every certificate step, not a tail call in OCaml, so a long enough certificate overflows the
   stack outright). stack_overflow_trans.cvc5pf is generated by generate.py: a small,
   genuinely-needed refutation (a0/r0/tFinal) followed by N independent `refl`+`refl`+`trans`
   triples (each deriving "x=x" from two copies of "x=x" - a genuine, if repetitive, use of the
   TransAST "transitivity over terms" rule), none of which the refutation actually needs.
   Regenerate with a larger N if a given N happens not to overflow the pre-fix stack on your
   system (`python3 generate.py 20000 > stack_overflow_trans.cvc5pf`) - keep in mind checking
   time scales worse than linearly with N even on the fixed code, so very large N may just time
   out instead of demonstrating anything new. *)

Add Rec LoadPath "../../../../src" as SMTCoq.
Require Import SMTCoq.SMTCoq.
Require Import Bool.

Section StackOverflowTrans.
  Verit_Checker "stack_overflow_trans.smt2" "stack_overflow_trans.cvc5pf".
End StackOverflowTrans.
