'''
This script is for parsing the coq code (from the file generated by file_generate.py) into comments needed for debugging.
'''

from parse_functions import *
from file_generate import *

'''
Captures coq output and parses it.
'''
def main():
    coq_op = run_coqc(full_name)
    print(coq_op)

if __name__ == "__main__":
    main()