'''
This script is for finding possible issues with the pf file by using a heuristic search for possible problem areas in the .txt file generated by parse_driver.py
Needs parse_driver.py AND file_generate.py to be run before being able to run (makefile will take care of this).

How it works:

'''

from parse_driver import *

def main():

    with open(parse_name, 'r') as f:
        # get all lines from basename.txt
        parse_op = f.read()
    
    #print(parse_op)

    # get the last state
    lline = parse_op.rsplit('\n',1)[1]
    num_state = re.search(r's(\d+)', lline).group(1)

    # put all the states in a list
    states_str = parse_op.split('\n', 8)[8]
    states = re.findall('((?:[^\n]+\n?){1,4})', states_str)


    # list containing all possible states where a problem occured
    # start with assuming every state is a possible issue
    prob_states = list(range(1, int(num_state) + 1))

    # functions to narrow down that list
    has_zero(prob_states, states)
    
    # print final list
    print_probs(prob_states, states)


# checks if the problem states have a 0. if they don't, remove from possible problem states.
def has_zero(prob_states, states):
    for i in range(len(prob_states)):
        cur = states[prob_states[i]-1]
        if (cur.find(0) != -1):
            prob_states.pop(i)


# takes a list containing possible problem states and a list with all states, prints them all in format
def print_probs(prob_states, states):
    print("Possible problem states:")
    for i in range(len(prob_states)):
        print(states[prob_states[i] -1])


if __name__ == "__main__":
    main()