'''
This script is for parsing the coq code (from the file generated by file_generate.py) into comments needed for debugging.
Needs file_generate.py to be run before being able to run (makefile will take care of this).
'''

from parse_functions import *
from file_generate import *

'''
Captures coq output and parses it.
'''
def main():
    coq_op = run_coqc(full_name)
    
    # extract number of certifcates
    certnum = parse_coq_certnum(coq_op)

    # string where all comments will go before being written
    parsed = ""

    # split before s0, parse initial_op
    delim = 's0 = \n'
    cert_list = coq_op.split(delim)
    initial_op = cert_list[0]

    parsed += parse_init_op(initial_op) + "\n\n"

    # set up s0 into the correct formate for parse_state_op
    s0 = "s0 = \n" + cert_list[1].split("= ")[0]
    parsed += parse_state_op(s0) + "\n\n"

    # set up first step into correct format for parse_Step
    step1 = "= " + cert_list[1].split("= ")[1]
    step1 = step1[:len(step1)-4]  #cut off the trailing '\n s1'
    parsed += "1.\n" + parse_Step(step1) + "\n"

    
    # for every certificate after s0,
    for i in range(1, (certnum+1)): 
        delim = 's' + str(i) + " = \n"

        # if not last element,
        if(i != certnum):
            cert_list = coq_op.split(delim)

            #everything after s%d
            split_op = cert_list[1]

            # extract state
            state = split_op.split("= ")[0] # cut off step
            state = delim + state # add on s%d = \n
            parsed += parse_state_op(state) + "\n"


            #signal next step
            parsed += "\n" + str(i+1) + ".\n"

            # extract step
            step = "= " + split_op.split("= ")[1] # cut off state
            step = step[:len(step)-4] #cut off the trailing \n s%d'
            parsed += parse_Step(step) + "\n"

        # final state    
        else:
            cert_list = coq_op.split(delim)

            #everything after s%d
            split_op = cert_list[1]

            # extract state
            state = delim + split_op # add on s%d = \n
            parsed += parse_state_op(state)        
    
    # empty file
    with open(parse_name, "w") as f:
        f.close()
    
    # write everything
    with open(parse_name, "r+") as f:
        f.write(parsed)


if __name__ == "__main__":
    main()